### ISSUE TITLE
Rust: cache cargo cross

### ISSUE THREAD

**Issue by idelvall** [earthly/lib#34]
[Cargo cross](https://github.com/cross-rs/cross) requires docker or podman installed.
Earthly doesn't support calling a `FUNCTION` within a `WITH DOCKER` statement, so there the rust library cannot be used to cache cargo cross runs as it is.

**Comment by joepio** [comment]
Thanks @idelvall!

```
IMPORT github.com/earthly/lib/rust:nacho/with_docker AS rust
```

```
  WITH DOCKER
    DO rust+CARGO --args="cross" --$with_docker="--load ghcr.io/cross-rs/$TARGET:v0.2.5"
  END
```

Unfortunately, still results in `only one RUN command allowed in WITH DOCKER`

```
            _unknown *failed* | build target: build main: failed to solve: Earthfile line 29:2 apply BUILD +docker-musl: earthfile2llb for +docker-musl: Earthfile line 78:2 copy artifact: apply build +cross-build: earthfile2llb for +cross-build: /var/folders/4j/nbs48t1s7l52fvv4vfnrrymw0000gp/T/earthly-git3268833410/Earthfile line 159:4 only one RUN command allowed in WITH DOCKER
            _unknown *failed* | in		github.com/earthly/lib/rust:nacho/with_docker+CHECK_INITED (/var/folders/4j/nbs48t1s7l52fvv4vfnrrymw0000gp/T/earthly-git3268833410/Earthfile line 81:4)
            _unknown *failed* | called from	github.com/earthly/lib/rust:nacho/with_docker+RUN_WITH_CACHE (/var/folders/4j/nbs48t1s7l52fvv4vfnrrymw0000gp/T/earthly-git3268833410/Earthfile line 52:4)
            _unknown *failed* | called from	github.com/earthly/lib/rust:nacho/with_docker+CARGO (Earthfile line 52:4) --TMP_FOLDER= --args=cross --output=
            _unknown *failed* | called from	github.com/atomicdata-dev/atomic-data-rust:develop+cross-build --TARGET=x86_64-unknown-linux-musl
            _unknown *failed* | in		github.com/atomicdata-dev/atomic-data-rust:develop+docker-musl --TARGET=x86_64-unknown-linux-musl --tags=joepmeneer/atomic-server:develop
            _unknown *failed* | in		github.com/atomicdata-dev/atomic-data-rust:develop+docker-all
```

**Comment by joepio** [comment]
Changes on my end: https://github.com/atomicdata-dev/atomic-server/pull/735

**Comment by idelvall** [comment]
You need to remove the[ WITH DOCKER on your end](https://github.com/atomicdata-dev/atomic-server/blob/8b1e55ca633fcf3c2d9fa2617bbdbbb5478f2ea6/Earthfile#L49),  the function will create it internally:

**Comment by joepio** [comment]
Thanks! Works, leads to [new err](https://cloud.earthly.dev/builds/24331ed1-bdab-4325-bc76-e86e40e0d934).

Seems like it's calling `cargo cross` instead of `cross`.

I'm gonna try `+RUN_WITH_CACHE`

**Comment by joepio** [comment]
Hmm [nope](https://cloud.earthly.dev/builds/d68fbb40-87b6-4271-b48f-aab3b67004b5)...

```
     58  Error: async earthfile2llb for +docker-musl: Earthfile line 74:2 copy artifact: apply build +cross-build: earthfile2llb for +cross-build: /tmp/earthly-git3082292346/Earthfile line 82:4 apply ARG: value not supplied for required ARG: command
     59  in             github.com/earthly/lib/rust:nacho/with_docker+RUN_WITH_CACHE (Earthfile line 49:2) --command=
     60  called from    github.com/atomicdata-dev/atomic-server:improved-docker-rust-cache+cross-build --TARGET=armv7-unknown-linux-musleabihf
     61  in             github.com/atomicdata-dev/atomic-server:improved-docker-rust-cache+docker-musl --TARGET=armv7-unknown-linux-musleabihf --tags=joepmeneer/atomic-server:improved-docker-rust-cache
     62  View logs at https://cloud.earthly.dev/builds/d68fbb40-87b6-4271-b48f-aab3b67004b5

```

**Comment by joepio** [comment]
made a bunch of changes, but now it can't find docker:
 
```
        +cross-build | Error:
        +cross-build |    0: no container engine found

        +cross-build | Suggestion: is docker or podman installed?
        +cross-build | earthly debugger | Command /bin/sh -c 'set -e; mkdir -p $CARGO_HOME; printf "Running:\n      $command\n"; eval $command' failed with exit code 1
        +cross-build | Entering interactive debugger
        +cross-build |
```

Still no access to docker it seems. 

```
  DO rust+RUN_WITH_CACHE --$with_docker="--load ghcr.io/cross-rs/$TARGET:v0.2.5" --command="cross build --target $TARGET --release" --output="target/$TARGET/release/atomic-server"
```

**Comment by joepio** [comment]
Some of the runs keep going for hours, getting stuck, apparently

https://cloud.earthly.dev/ontola/builds/2dd9a510-d201-4963-a552-c6abf7f5749a

**Comment by joepio** [comment]
A user asked this: 

> One bit I can't figure out is how to set the path when creating a new document in the UI.  It always uses "Untitled Document" and appends a random string to make it unique.

**Comment by idelvall** [comment]
Hi @joepio, I've been working on a different approach. Let me know what do you think: https://github.com/earthly/lib/pull/39

**Comment by joepio** [comment]
Yay, seems to work! https://cloud.earthly.dev/builds/eeb7ac2a-0cca-41e9-86de-0e83751c1705

**Comment by idelvall** [comment]
Hey @joepio , i've seen in those logs that a significant number of crates are compiled by cross. Wondering of cross is designed to cache compiled artifacts, and if we can mount the Earthly caches into the cross container

**Comment by AlexMikhalev** [comment]
Cargo can fetch packages before build, for example for Atomic earhtfile the changes will be:
```
source:
  FROM +install
  COPY --keep-ts Cargo.toml Cargo.lock ./
  COPY --keep-ts --dir server lib cli  ./
  COPY browser+build/dist /code/browser/data-browser/dist
  DO rust+CARGO --args=fetch 
```
and then add offline:
```
build:
  FROM +source
  DO rust+CARGO --args="build --offline --release" --output="release/[^/\.]+"
```
My concern is that even way simpler step:
```
install:
  RUN apt-get update -qq
  RUN rustup component add clippy
  RUN rustup component add rustfmt
  RUN cargo install cross
  DO rust+INIT --keep_fingerprints=true
```
isn't cached between between build and test stages: I run +build and when I run +test +install re-runs with fetching all updates. 
Another avenue to speed up rust compilation inside earthly satellite can be to use cargo vendor command and then re-mount target folder accross build/test. One more avenue - use panamax.rs to sync crates.io to local instance before all builds.

**Comment by joepio** [comment]
I don't think they are running in parallel [here](https://cloud.earthly.dev/builds/9287f424-5091-4564-b204-c82967c4a46f). 

```
docker-all:
  BUILD --platform=linux/amd64 +docker-musl --TARGET=x86_64-unknown-linux-musl
  BUILD --platform=linux/arm/v7 +docker-musl --TARGET=armv7-unknown-linux-musleabihf
  BUILD --platform=linux/arm64/v8 +docker-musl --TARGET=aarch64-unknown-linux-musl
```

This should probably happen in parallel, right? @idelvall

**Comment by idelvall** [comment]
> I don't think they are running in parallel [here](https://cloud.earthly.dev/builds/9287f424-5091-4564-b204-c82967c4a46f).
> 
> ```
> docker-all:
>   BUILD --platform=linux/amd64 +docker-musl --TARGET=x86_64-unknown-linux-musl
>   BUILD --platform=linux/arm/v7 +docker-musl --TARGET=armv7-unknown-linux-musleabihf
>   BUILD --platform=linux/arm64/v8 +docker-musl --TARGET=aarch64-unknown-linux-musl
> ```
> 
> This should probably happen in parallel, right? @idelvall

Yes they should. Let me see

**Comment by idelvall** [comment]
Hi @joepio, `WITH DOCKER` is affected by a parallelization issue. https://github.com/earthly/earthly/issues/3808
I've was able to overcome it by using VERSION 0.8 and making sure the target has not an inner `FROM` (as yours does)

**Comment by idelvall** [comment]
fixed by https://github.com/earthly/lib/releases/tag/3.0.0
