### ISSUE TITLE
`billing+active-users` target only works for gitlab/github

### ISSUE THREAD

**Issue by rrjjvv** [earthly/lib#49]
Self-hosted satellites now have public documentation.  Pricing is currently documented as being based on user count, and go on to say
> If you would like to estimate the number of users that a project has according to how we track users, please check out the [github.com/earthly/lib/billing+active-users](https://github.com/earthly/lib/tree/main/billing#active-users) target.

That target currently only works for gitlab and github.  It's likely that users/evaluators of self-hosted satellites are doing so due to having self-hosted CI (such as myself), so it would be nice if the target worked with self-hosted git solutions as well.

**Comment by idelvall** [comment]
Fixed by https://github.com/earthly/lib/pull/50
