### ISSUE TITLE
Earthfile does not have a `VERSION`

### ISSUE THREAD

**Issue by brumhard** [earthly/lib#5]
When using the commands provided in the Earthfile I get the following error:
```
Warning: No version specified in github.com/earthly/lib/Earthfile. Implying VERSION 0.5, which is not the latest available. Please note that in the future, the VERSION command will be required for all Earthfiles.
```

Not sure if there's a reason for that.

**Comment by alexcb** [comment]
fixed in f39d559875113df322459259bf71e7dde68d07b2; apologies for the delay on this -- we'll try better to watch this repo for issues.
