### ISSUE TITLE
Upgrade docker-compose

### ISSUE THREAD

**Issue by v-yarotsky** [earthly/lib#6]
Currently, version 1.27.4 is [installed](https://github.com/earthly/lib/blob/b1834f029ce4ff9953952c611012c055520b8b60/install-dind.sh#L48-L54), it's almost 2 years old and doesn't support cool features like [this](https://docs.docker.com/compose/release-notes/#features).

**Comment by alexcb** [comment]
docker-compose has been updated to 1.29 in 635a7da9970862d2bfa6f4c73cb597d566fa13ea

https://github.com/linuxserver/docker-docker-compose doesn't have any of the 2.X releases yet (technically they do, but they are all marked as pre-releases).

I worry about having these versions differ depending on which platform is detected -- we should do some more testing on them to see if we can upgrade them all at once.

**Comment by EamonKeane** [comment]
fwiw, this works for me and gives me docker compose v2.17.2. That repo you referenced was deprecated in February also it seems (https://github.com/linuxserver/docker-docker-compose).

```  
FROM alpine
DO github.com/earthly/lib+INSTALL_DIND
```

**Comment by alexcb** [comment]
The readme on https://hub.docker.com/r/earthly/dind has been updated to reflect the new dind image tags.

Here are the current docker-compose versions in these images:

```
$ docker run --rm earthly/dind:alpine-3.18-docker-23.0.6-r4 docker compose version
Docker Compose version v2.17.3
```

```
$ docker run --rm earthly/dind:ubuntu-20.04-docker-24.0.5-1 docker compose version
Docker Compose version v2.20.2
```

```
$ docker run --rm earthly/dind:ubuntu-23.04-docker-24.0.5-1 docker compose version
Docker Compose version v2.20.
```
